.TH "matrix< type >" 3 "2018年 八月 31日 星期五" "Version 1.0" "matrix library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matrix< type > \- matrix 矩阵类的简单实现  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Matrix\&.h>\fP
.SH "详细描述"
.PP 

.SS "template<class type>
.br
class matrix< type >"
matrix 矩阵类的简单实现 

.SH "作者"
.PP 
由 Doyxgen 通过分析 matrix library 的 源代码自动生成\&.
